### ISSUE TITLE
Vervang hoofdstuktitles in de appendix door "Appendix A" i.p.v. "Hoofdstuk A"

### ISSUE THREAD

**Issue by GXGOW** [HoGentTIN/bachproef-latex-sjabloon#10]
Dit kan bereikt worden door het volgende lijn toe te voegen in bachproef/bachproef-tin.tex (lijn 104):
```
\appendix
\renewcommand\chaptername{Appendix}
```
Hierdoor verandert de heading in de appendices van
![before](https://user-images.githubusercontent.com/14166923/40587932-7083092c-61d6-11e8-961a-4e9f252a0ed8.png)
naar
![image](https://user-images.githubusercontent.com/14166923/40587939-8e42c59c-61d6-11e8-850d-0b0256a071d6.png)

Sommige promotoren gaven hierover de opmerking dat dit iets duidelijker is. Daarom dat ik deze aanpassing even suggereer.

**Comment by bertvv** [comment]
Goede suggestie, bedankt! Ik pas het zo aan.

**Comment by bertvv** [comment]
Aangepast in 56c8014
