### ISSUE TITLE
Referenties met JabRef

### ISSUE THREAD

**Issue by MatthiasDh** [HoGentTIN/bachproef-latex-sjabloon#11]
De layout van een bachelorproefvoorstel wordt bepaald door "voorstel.cls". Dit bestand zorgt er ook voor dat de referenties ingeladen worden wanneer de pdf gegenereerd wordt. (sectie onderaan in dit bestand)

Wanneer ik mijn .tex bestand omzet naar pdf worden deze referenties niet zichtbaar. Wanneer ik de regels in "voorstel.cls" die voor de referenties zorgen gewoon bovenaan in mijn .tex overneem dan werkt dit wel foutloos. Onderstaande kan u zien hoe mijn header er momenteel uitziet.

> \documentclass[fleqn,10pt]{voorstel}
\RequirePackage[backend=biber,style=apa]{biblatex}
\DeclareLanguageMapping{dutch}{dutch-apa}
\addbibresource{voorstel.bib}

Heb al van verschillende studenten in het verleden gehoord dat ze problemen hadden met hun referenties, misschien om deze reden?

NOTE: Dit is uitgevoerd op een macbook pro

**Comment by bertvv** [comment]
Ik kan dit niet reproduceren. Bij het voorbeelddocument wordt de bibliografie meteen getoond als ik het compileer in TeXstudio.

Soms helpt het om de bibliografie expliciet te genereren (in TeXstudio met F8) en opnieuw te compileren (F5).

**Comment by bertvv** [comment]
Je moet er ook op letten dat de bibliografie door biber wordt gegenereerd, niet door bibtex. In TeXstudio: Options > Configure > Build > Default Bibliography Tool: "txs:///biber"

Kan je eens nakijken of het hier aan ligt? En indien niet, kan je eens een logbestand van het compilatieproces toevoegen aan dit Issue?

**Comment by bertvv** [comment]
oeps, verkeerde issue gerefereerd in 56c8014

**Comment by MatthiasDh** [comment]
Dit probleem heeft zichzelf opgelost wanneer ik "naam_voorstel.aux" & "naam_voorstel.bbl" heb gedelete. Is hier enige verklaring voor waarom dit probleem voorkwam ?

**Comment by bertvv** [comment]
Niet specifiek. Wellicht zijn de hulpbestanden .aux en .bbl gebaseerd op een oudere versie van het .tex-bestand en zijn die bij compilatie niet meer onderling consistent waardoor de compiler in de war geraakt is...

Dan sluit ik deze issue af.
