### ISSUE TITLE
poster: incompatible color definitions

### ISSUE THREAD

**Issue by nvanderperren** [HoGentTIN/bachproef-latex-sjabloon#16]
Ik krijg steeds de foutmelding dat de kleurendefinities in de poster incompatibel zijn in texstudio.

<img width="563" alt="Schermafbeelding 2019-09-02 om 10 18 47" src="https://user-images.githubusercontent.com/17183054/64100069-19d38c80-cd6b-11e9-88ed-06e4d80eb83c.png">

**Comment by bertvv** [comment]
In het vernieuwde sjabloon voor de poster zou dit intussen moeten opgelost zijn.
