### ISSUE TITLE
Stijl van listings tabel ook instellen in template

### ISSUE THREAD

**Issue by BrackeNavaron** [HoGentTIN/bachproef-latex-sjabloon#19]
De huidige template van de bachelorproef heeft een dependency op de `listings` package.

Indien er via het `\lstlistoflistings` commando een lijst wordt ingevoegd, krijgt deze lijst niet dezelfde stijl zoals de Lijst van Figuren en Lijst van Tabellen.

Het template voorziet best ook de stijl voor dit commando.

**Comment by bertvv** [comment]
Er is een nieuw sjabloon gepubliceerd waardoor deze issue niet meer relevant is.
