### ISSUE TITLE
Installatie Perl

### ISSUE THREAD

**Issue by kwinteng** [HoGentTIN/bachproef-latex-sjabloon#2]
Op windows is Perl niet automatisch geinstalleerd
Latexmk vraagt naar Perl

Misschien is het handig om dit in de Readme op te nemen.
Zelf heb ik gekozen voor ActivePerl (http://www.activestate.com/activeperl)
En de installatie vraagt er niet naar maar de PC moet opnieuw opgestart worden om Perl aan de PATH variable toe te voegen.

**Comment by bertvv** [comment]
Ik denk dat ik beter aanbeveel om toch pdflatex te gebruiken, zeker vanuit een IDE als TexStudio. Op Windows, als pdflatex uitgevoerd wordt, wordt indien nodig de package manager van MikTeX getriggerd om alle nodige dependencies voor een LaTeX-document te installeren. Volgens mij wordt dan ook zo nodig Perl geïnstalleerd. Dit lijkt in elk geval te werken bij de studenten die ik in onderzoekstechnieken opvolg.
