### ISSUE TITLE
XeLaTeX rendert sans-serif en bold fonts niet bij voorstel (PdfLaTeX wel)

### ISSUE THREAD

**Issue by DanteDeRuwe** [HoGentTIN/bachproef-latex-sjabloon#21]
Wanneer ik compile met xelatex _(zoals aangegeven in de README)_ rendert `\sffamily` niet naar behoren. Ook de bold fonts renderen verkeerd. Zie hieronder:

![image](https://user-images.githubusercontent.com/23363437/100012444-9a006a80-2dd3-11eb-8f33-ba51c844ed46.png)

Met pdflatex krijg ik wel het gewenste resultaat.

Dit geldt zowel voor TexStudio als via CLI

**Comment by bertvv** [comment]
Ik krijg dit inderdaad ook. Ik denk dat we het sjabloon moeten herschrijven om XeLaTeX-compatibel te worden of een ander template gebruiken...

**Comment by bertvv** [comment]
Er is intussen een nieuw sjabloon gepubliceerd met een volledig bijgewerkte vormgeving.
