### ISSUE TITLE
/usr/bin/docker: No such file or directory

### ISSUE THREAD

**Issue by Olivier-OG** [HoGentTIN/bachproef-latex-sjabloon#29]
Op (mijn) mac is docker installed op `/usr/local/bin/docker` in plaats van `/usr/bin/docker`.
Met homebrew op `/opt/homebrew/bin/docker`.

Heb dit eens opgezocht en het lijkt mij wel dat `/usr/local/bin/docker` de default install locatie is zoals ze hier aanraden:
https://docker-docs.uclv.cu/engine/install/binaries/#install-client-binaries-on-macos

```
oliviergilquin@MacBook-Pro bachproef % ./make_voorstel.sh
Using Docker
./make_voorstel.sh: line 21: /usr/bin/docker: No such file or directory
```

**Comment by bertvv** [comment]
/usr/bin/docker zomaar vervangen door /usr/local/bin/docker lijkt me niet de correcte oplossing en zal in andere situaties dan de jouwe niet werken. Ik zal een extra conditie toevoegen die checkt op beide mogelijkheden.
