### ISSUE TITLE
Overlap of numbers and caption in list of listings (and possibly also list of figures, tables)

### ISSUE THREAD

**Issue by bertvv** [HoGentTIN/bachproef-latex-sjabloon#37]
When the numbering of a listing becomes too wide, it overlaps with the description:

![image](https://github.com/HoGentTIN/latex-hogent-bachproef/assets/438140/f9f61109-975b-4b40-a0f1-342414717765)

Possible solution can be found here: https://tex.stackexchange.com/questions/495172/space-between-number-and-item-in-list-of-listings

**Comment by thomasaelbrecht** [comment]
`tocstyle` seems to be deprecated, we must replace it with `tocbasic` or `scrwfile`: https://tex.stackexchange.com/questions/565279/missing-tocstyle-sty-file.

**Comment by bertvv** [comment]
Fixed in 9b091f4e2f625aa2c51046775c136bd9e28f4f1d
