### ISSUE TITLE
Bijlagen of appendices toevoegen

### ISSUE THREAD

**Issue by kwinteng** [HoGentTIN/bachproef-latex-sjabloon#5]
Is er een specifieke manier om bijlagen toe te voegen?
Voorlopig heb ik:
\usepackage[toc,page]{appendix} toegevoegd aan structure.tex
en
 \begin{appendices}
\input{eerstebijlage}
\input{tweedebijlage}
\end{appendices}
aan bachproef-tin.tex
Daarnaast is ook de vraag: in welke structuur moet dit
references, list of figures, list of tables, appedix of
references, appedix, list of figures, list of tables

**Comment by bertvv** [comment]
Normaal moet je enkel het commando \appendix toevoegen voor de eerste bijlage. Daarna zijn hoofdingen met \chapter{} een bijlage (met letter A, B, C, enz)

De appendix-package is dus in principe niet nodig.

Je laatste vraag begrijp ik niet...

**Comment by kwinteng** [comment]
In de APA stijl is er een volgorde om verschillende dingen weer te geven zoals referenties appendices, figuren en tabellen.
Nu weet ik niet of ik eerst de referenties dan de appendices en dan de figuren en tabellen moet doen of eerst de referenties, de figuren en tabellen en als laatste de appendices.

**Comment by bertvv** [comment]
Dat maakt voor ons niet zo veel uit. We zijn al blij als de layout goed is.
