### ISSUE TITLE
Pagina hoofding verkeerd bij inleiding

### ISSUE THREAD

**Issue by thomasaelbrecht** [HoGentTIN/bachproef-latex-sjabloon#9]
Bij dit sjabloon komt er een verkeerde hoofding op sommige pagina's waar bijvoorbeeld geen section op aanwezig is, er staat dan links of rechts LIJST VAN TABELLEN i.p.v. de naam van het hoofdstuk. Dit probleem doet zich niet voor in andere hoofdstukken en ook niet als ik in de inleiding ```\chapter*{Inleiding}``` vervang door ```\chapter{Inleiding}```. Maar bij dit laatste commando begint de telling van de hoofdstukken dan wel vanaf de inleiding i.p.v. stand van zaken.

Is hier een oplossing voor?

**Comment by KarineVanDriessche** [comment]
Dag Thomas,


ik begrijp niet goed waarover je het hebt?

Ik heb hier precies maar een halve mail!

Let wel op: ik ken niets van latex. Dus geef mij je draft in PDF.


mvg

Karine Van Driessche

________________________________
Van: Thomas Aelbrecht <notifications@github.com>
Verzonden: woensdag 25 april 2018 15:01:54
Aan: HoGentTIN/bachproef-latex-sjabloon
CC: Subscribed
Onderwerp: [HoGentTIN/bachproef-latex-sjabloon] Pagina hoofding verkeerd bij inleiding (#9)


Bij dit sjabloon komt er een verkeerde hoofding op sommige pagina's waar bijvoorbeeld geen section op aanwezig is, er staat dan links of rechts LIJST VAN TABELLEN i.p.v. de naam van het hoofdstuk. Dit probleem doet zich niet voor in andere hoofdstukken en ook niet als ik in de inleiding \chapter*{Inleiding} vervang door \chapter{Inleiding}. Maar bij dit laatste commando begint de telling van de hoofdstukken dan wel vanaf de inleiding i.p.v. stand van zaken.

Is hier een oplossing voor?

**Comment by thomasaelbrecht** [comment]
@KarineVanDriessche Ik heb het je per mail gestuurd.

**Comment by KarineVanDriessche** [comment]
Dag Thomas,


in bijlage een cursus van Latech: misschien kan je aan de hand hiervan het probleem oplossen.


mvg

Karine VD

________________________________
Van: Thomas Aelbrecht <notifications@github.com>
Verzonden: woensdag 25 april 2018 15:57:58
Aan: HoGentTIN/bachproef-latex-sjabloon
CC: Karine Van Driessche; Mention
Onderwerp: Re: [HoGentTIN/bachproef-latex-sjabloon] Pagina hoofding verkeerd bij inleiding (#9)


@KarineVanDriessche<https://github.com/KarineVanDriessche> Ik heb het je per mail gestuurd.

**Comment by thomasaelbrecht** [comment]
@KarineVanDriessche Ik zie geen bijlage...
@eothein of @bertvv Kunnen jullie misschien hulp bieden? Jullie kennen waarschijnlijk meer van Latex dan ik...

**Comment by eothein** [comment]
Ik bekijk morgen eens het probleem

**Comment by eothein** [comment]
Kan je me eens de link van jouw repo bezorgen? Met het sjabloon vind ik geen probleem. Kan je dan eens precies duiden waar het bij jou fout loopt?

Mvg Jens Buysse

**Comment by thomasaelbrecht** [comment]
Hierbij mijn repository: https://github.com/thomasaelbrecht/bachelorproef

Bij mij loopt het zowel bij het sjabloon als bij mijn bp mis bij het maken van de hoofding. Als je de pdf maakt, krijg je bijvoorbeeld bovenaan pagina 18 _LIJST VAN TABELLEN_ terwijl daar eigenlijk _Hoofdstuk 0. Inleiding_ moet staan. Hetzelfde doet zich voor op pagina 14 van het sjabloon. Zie screenshots hieronder, beide genomen uit de Inleiding. Hopelijk begrijp je nu beter wat ik bedoel?

Mvg
Thomas Aelbrecht

<img width="547" alt="Screenshot fout in mijn bp" src="https://user-images.githubusercontent.com/18249310/39444055-b64e6cec-4cb6-11e8-9bdb-f6d2e635f6db.png">

<img width="809" alt="Screenshot fout in sjabloon" src="https://user-images.githubusercontent.com/18249310/39444112-d85ecd40-4cb6-11e8-84ef-fe8e08dc85ba.png">

**Comment by bertvv** [comment]
Het is inderdaad beter om het hoofdstuk met `\chapter{Inleiding}` te beginnen ipv `\chapter*{}`. Ik zal dit aanpassen.

`\chapter*{}` zorgt er voor dat dat hoofdstuk niet opgenomen wordt in de inhoudstafel en dus worden de hoofdingen ook niet gegenereerd.

**Comment by eothein** [comment]
Trouwens @thomasaelbrecht , je vraagstelling is zo veel duidelijker :p

**Comment by thomasaelbrecht** [comment]
Bedankt @eothein, ik wist niet goed hoe het hier te omschrijven/verwoorden. Altijd ruimte voor verbetering bij mij!
